spring:
  application:
    name: sinta-se-bem-app

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.xml
    default-schema: public
